trigger:
- main

pool:
  name: Default # use this if using self-hosted
  # pool: 'windows-latest' # use this if using Microsoft-hosted

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x' # Or your .NET SDK version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build
  displayName: 'Build project'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
