trigger:
- main

pool:
  name: Default # use this if using self-hosted
  #pool:vmImage: 'windows-latest' # use this if using Microsoft-hosted

steps:


- script: dotnet build
  displayName: 'Build project'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
